version: '3'

volumes:
  cache:
    driver: local
  postgres-data:

services:
  minio:
    image: minio/minio
    container_name: minio-habr
    environment:
      - MINIO_ROOT_USER=minioadmin
      - MINIO_ROOT_PASSWORD=minioadmin
    volumes:
      - ./minio-data:/data
    ports:
      - "9000:9000"
    command: server /data

  minio-client:
    image: minio/mc
    container_name: minio-client-habr
    entrypoint: [ "/bin/sh", "-c" ]
    command: >
      "sleep 10;
      mc alias set myminio http://minio:9000 minioadmin minioadmin &&
      tail -f /dev/null"
    depends_on:
      - minio
  redis:
    image: redis:7.2-rc-alpine
    restart: always
    container_name: redis-habr
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning --requirepass cXdlYXNkeGNjZGZm
    volumes:
      - cache:/data
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq-habr
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - "5672:5672"
      - "15672:15672"
  postgres:
    image: postgres:13
    container_name: postgres
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=habr_application
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"